### ISSUE TITLE
question

### ISSUE THREAD

**Issue by antarus** [hipster-labs/generator-jhipster-spring-cloud-stream#2]
Hello, this is not an anomaly but a question.
Do you have a place or we could discuss who does what? because what did @pascalgrimaud  yesterday, I did it also and it's a shame. In my case it allows me to learn node and the generator but I think we could be more efficient.
And if possible as long as you are between French and it's for planning, do it in French ... I understand very well written English but to write, speak or hear it, I am close to zero: D

In the meantime, I will look and try to add / modify properties in yaml files to add the rabbit configuration.

**Comment by deepu105** [comment]
Given this is a community please do keep it in English :)

**Comment by jdubois** [comment]
Yes we discuss in English, through GitHub, so everybody knows what's happening

**Comment by antarus** [comment]
Ok for English.
I never really work on github.
How do you manage the planning, decision, question without polluting the issue part?
Perhaps, we can create a room on https://gitter.im/?

**Comment by jdubois** [comment]
There is a gitter room but that's mostly for end-users.
Decisions and discussions are on GitHub tickets.

**Comment by pascalgrimaud** [comment]
@antarus : I'm really sorry, I should tell in the other ticket that I was starting to init the project. Now, it's done, but it's not finished. I will open another ticket here, to list all things to do before doing the 1st release 0.0.1

**Comment by antarus** [comment]
@pascalgrimaud No problem that allowed me to learn the generator :)

**Comment by danielpetisme** [comment]
Whoa, it's going faster than light!

As discussed in the core project, I won't have much time to spend on the build but I have already project using `scs-rabbit` so I would be very interested on testing this module.

Regarding the code coming from the sample app, I don't thinks there is anything complex but If you need a clarification on any point feel free to ask.

A said, I played with the yaml configuration, rabbit binder, etc. So let me know if you need help.

**Comment by pascalgrimaud** [comment]
TODO list here: https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/issues/4
So I'm closing this.
