### ISSUE TITLE
JHipster 5 compatibility

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/generator-jhipster-spring-cloud-stream#25]
@antarus : with the new release of JHipster 5, do you have time to check if everything is OK ?

**Comment by PierreBesson** [comment]
We also need to upgrade to Spring cloud stream 2 !

**Comment by antarus** [comment]
Hello, I have not had time to look at jhipster 5 yet.
I follow the progress of the project, but I haven't even taken the time to test it yet. I think it would solve some of my problems, but i have a big project to finish this month ..
I don't know when I will have time to look..
sorry

**Comment by pascalgrimaud** [comment]
No worry @antarus it's open source!
I opened this ticket just to not forget. We can do this when we'll have time :)

**Comment by flefevre** [comment]
Hello, I have seen the new version of JHipster 5, released after the Jhipstercon. Is it compatible now with Jhipster 5? Will it be usefull for you I create a basic Jhipster5 project, adn add your module to test?

**Comment by pascalgrimaud** [comment]
Yes, if you can test, plz :)

**Comment by flefevre** [comment]
For testing purposes, I have created a project from scratch. here in my github [1]

- creation of new jhipster project under j5 with 5.1.0 jhipster geenrator
- add a blog.jdl
- update the app
- run .mvnw
- test the app

then i have followed readme provided here [2]

i have started the rabbitmq docker
and run again the app

how can I test the configuration?
is there a snipped of code, that I have to integrate?
can you give me advice here?

Thanks

What happens if I activate the Kafka layer at the root project generation: will it be in conflict with your rabbitmq?

[1]: https://github.com/flefevre/jhipsterRabbitmq
[2]: https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream

**Comment by pascalgrimaud** [comment]
@flefevre : if I remember well (I'm not the one who codes the main part), you should be able to send message to RabbitMQ, using Swagger.

For the other question about Kafka, sorry no idea. Never tested the combination of both

**Comment by flefevre** [comment]
So I connect to my browser http://localhost:15672/#/ with guest:guest credentials
Then I go the rest swagger api, and create POST /api/messages with the following body
`JhiMessage {
    "body": "bodytest",
    "title": "titletest"
  }`

I have got a reply
{
  "pragma": "no-cache",
  "date": "Fri, 03 Aug 2018 15:01:49 GMT",
  "x-content-type-options": "nosniff",
  "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
  "connection": "keep-alive",
  "content-length": "0",
  "x-xss-protection": "1; mode=block",
  "expires": "0",
  "content-type": null
}
when I have look to the web rabbitmq interface, I have seen a pick of One message

Moreover when I have look to the rest swagger GET /api/messages 
`[
  {
    "body": "string",
    "title": "string"
  }
]`

So it returns me the message that I have been sent throw Rabbitmq.

So for me, it seems to works !

**Comment by pascalgrimaud** [comment]
oh it works ! nothing to do here with JHipster v5 so ?

**Comment by flefevre** [comment]
Perhaps it will be good to reference your module in the jhsiper market app, when we create a project it seems not to be reference
But seems fully functionnal for me

**Comment by pascalgrimaud** [comment]
yes, I need to do a new release, with jhipster-5 as keywords in package.json

**Comment by pascalgrimaud** [comment]
oh, nothing... just completely forgot to do it
Will do it soon

**Comment by pascalgrimaud** [comment]
I tested everything and it works fine.
There is a new release: v1.0.0

Thanks for helping @flefevre
